
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: yarn build
      
      - run: |
          cd dist
          echo '---' >> 404.html
          echo 'permalink: /404.html' >> 404.html
          echo '---' >> 404.html
          cat index.html >> 404.html

      - persist_to_workspace:
          root: dist
          paths:
            - ./*



  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo

    steps:

      - attach_workspace:
          at: dist
      
      - run: ls dist

      
      - run: |
          git config --global user.email bot@circleci.com
          git config --global user.name bot
          
          cd dist
          git init
          git add .
          git commit -m "Deploy to Github Pages"
          git push --force --quiet "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" master:gh-pages > /dev/null 2>&1
          
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build